### ISSUE TITLE
Order gallery by most recent?

### ISSUE THREAD

**Issue by remy** [philhawksworth/viewportify#3]
Seems to make sense to put fresh content at the top. Like how poo rises in water. You want fresh at the top. Like cream on a mince pie. On the top. Where the top of the screen is. At the top.

**Comment by philhawksworth** [comment]
Agreed. I'll make that change. (and prefer the cream analogy to the poo one.)

**Comment by remy** [comment]
What analogy?

**Comment by philhawksworth** [comment]
New stuff now arrives at the top. Like cream on a mince pie.
